version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: /modules/gcp-single-node
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

  - package-ecosystem: terraform
    directory: /modules/aws-single-node
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
